import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SideNav from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next js News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Navbar />

          <div className="flex min-h-[calc(100vh-60px)]">
            <SideNav />

            {/* Scroll area */}
            <main className="flex-1 overflow-y-auto px-4 py-4">
              <div className="w-full md:max-w-6xl mx-auto">
                {children}
              </div>
            </main>

          </div>
      </body>
    </html>
  );
}
